export const INIT_CART_ITEMS = "INIT_CART_ITEMS";
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_EMPTY_ITEMS = "CART_EMPTY_ITEMS";
