export const HOME_SCREEN_ITEMS_REQUSET = "HOME_SCREEN_ITEMS_REQUSET";
export const HOME_SCREEN_ITEMS_SUCCESS = "HOME_SCREEN_ITEMS_SUCCESS";
export const HOME_SCREEN_ITEMS_FAIL = "HOME_SCREEN_ITEMS_FAIL";

export const FEED_SCREEN_ITEMS = "FEED_SCREEN_ITEMS";
