export const SEND_ORDER_NOTIFICATION_REQUEST =
  "SEND_ORDER_NOTIFICATION_REQUEST";
export const SEND_ORDER_NOTIFICATION_FAIL = "SEND_ORDER_NOTIFICATION_FAIL";
export const SEND_ORDER_NOTIFICATION_SUCCESS =
  "SEND_ORDER_NOTIFICATION_SUCCESS";

export const GET_ADMIN_REQUEST = "GET_ADMIN_REQUEST";
export const GET_ADMIN_SUCCESS = "GET_ADMIN_SUCCESS";
export const GET_ADMIN_FAIL = "GET_ADMIN_FAIL";
