export const ORDER_STATUS_REQUEST = "ORDER_STATUS_REQUEST";
export const ORDER_STATUS_SUCCESS = "ORDER_STATUS_SUCCESS";
export const ORDER_STATUS_FAIL = "ORDER_STATUS_FAIL";

export const ORDER_SAVE_FIRESTORE_REQUEST = "ORDER_SAVE_FIRESTORE_REQUEST";
export const ORDER_SAVE_FIRESTORE_SUCCESS = "ORDER_SAVE_FIRESTORE_SUCCESS";
export const ORDER_SAVE_FIRESTORE_FAIL = "ORDER_SAVE_FIRESTORE_FAIL";
export const ORDER_SAVE_FIRESTORE_RESET = "ORDER_SAVE_FIRESTORE_RESET";

export const ORDER_GET_USER_ORDERS_REQUEST = "ORDER_GET_USER_ORDERS_REQUEST";
export const ORDER_GET_USER_ORDERS_SUCCESS = "ORDER_GET_USER_ORDERS_SUCCESS";
export const ORDER_GET_USER_ORDERS_FAIL = "ORDER_GET_USER_ORDERS_FAIL";

export const ORDER_UPDATE_ORDERS_STATUS_REQUEST =
  "ORDER_UPDATE_ORDERS_STATUS_REQUEST";
export const ORDER_UPDATE_ORDERS_STATUS_SUCCESS =
  "ORDER_UPDATE_ORDERS_STATUS_SUCCESS";
export const ORDER_UPDATE_ORDERS_STATUS_FAIL =
  "ORDER_UPDATE_ORDERS_STATUS_FAIL";

export const ORDER_GET_ADMIN_ORDERS_REQUEST = "ORDER_GET_ADMIN_ORDERS_REQUEST";
export const ORDER_GET_ADMIN_ORDERS_SUCCESS = "ORDER_GET_ADMIN_ORDERS_SUCCESS";
export const ORDER_GET_ADMIN_ORDERS_FAIL = "ORDER_GET_ADMIN_ORDERS_FAIL";
