export const INIT_PAYMENTS_REQUEST = "INIT_PAYMENTS_REQUEST";
export const INIT_PAYMENTS_SUCCESS = "INIT_PAYMENTS_SUCCESS";
export const INIT_PAYMENTS_FAIL = "INIT_PAYMENTS_FAIL";

export const EXECUTE_REQUEST_JSON = "EXECUTE_REQUEST_JSON";

export const EXECUTE_PAYMENT_REQUEST = "EXECUTE_PAYMENT_REQUEST";
export const EXECUTE_PAYMENT_SUCCESS = "EXECUTE_PAYMENT_SUCCESS";
export const EXECUTE_PAYMENT_FAIL = "EXECUTE_PAYMENT_FAIL";

export const PAYMENT_CARD = "PAYMENT_CARD";
