export const CALC_RATE_REQUSET = "CALC_RATE_REQUSET";
export const CALC_RATE_SUCCESS = "CALC_RATE_SUCCESS";
export const CALC_RATE_FAIL = "CALC_RATE_FAIL";

export const CREATE_SHIPMENT_REQUSET = "CREATE_SHIPMENT_REQUSET";
export const CREATE_SHIPMENT_SUCCESS = "CREATE_SHIPMENT_SUCCESS";
export const CREATE_SHIPMENT_FAIL = "CREATE_SHIPMENT_FAIL";

export const PRINT_LABEL_REQUSET = "PRINT_LABEL_REQUSET";
export const PRINT_LABEL_SUCCESS = "PRINT_LABEL_SUCCESS";
export const PRINT_LABEL_FAIL = "PRINT_LABEL_FAIL";

export const CREATE_PICKUP_REQUSET = "CREATE_PICKUP_REQUSET";
export const CREATE_PICKUP_SUCCESS = "CREATE_PICKUP_SUCCESS";
export const CREATE_PICKUP_FAIL = "CREATE_PICKUP_FAIL";
